name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: default
          override: true
    - name: Run tests
      run: cargo test -- --nocapture
    - uses: actions/upload-artifact@v2
      with:
        name: pow-${{ matrix.os }}
        path: assets/pow/
