name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: default
          override: true
          components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Build Capstone (features = alloc + all-archs + sys-dyn-mem)
      run: cargo build --verbose --no-default-features --features alloc,all-archs,sys-dyn-mem
      working-directory: ./capstone
    - name: Build Capstone (features = all-archs + sys-dyn-mem)
      run: cargo build --verbose --no-default-features --features all-archs,sys-dyn-mem
      working-directory: ./capstone
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Clippy Lints
      run: cargo clippy --tests --examples
    - name: Check Formatting
      run: cargo fmt --all -- --check
