name: Create Test Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
        override: true
    - name: Install Cross
      run: cargo install cross

    - name: Build x86_64
      run: cross build --target x86_64-unknown-linux-gnu
      working-directory: assets/pow
    - uses: actions/upload-artifact@v2
      with:
        name: pow-linux-x86_64
        path: assets/pow
    - name: Clean
      run: cargo clean
      working-directory: assets/pow

    - name: Build i686
      run: cross build --target i686-unknown-linux-gnu
      working-directory: assets/pow
    - uses: actions/upload-artifact@v2
      with:
        name: pow-linux-i686
        path: assets/pow
    - name: Clean
      run: cargo clean
      working-directory: assets/pow

    - name: Build AArch64
      run: cross build --target aarch64-unknown-linux-gnu
      working-directory: assets/pow
    - uses: actions/upload-artifact@v2
      with:
        name: pow-linux-aarch64
        path: assets/pow
    - name: Clean
      run: cargo clean
      working-directory: assets/pow
